### PR TITLE
#390 change license.yml to use pip-license-checker action

### PR DESCRIPTION
**Pull request by scottwn**
- [x] I have added the tests to cover my changes.
- [x] I have updated the documentation and CHANGELOG accordingly.
- [x] I have read the CONTRIBUTING document.

### CODE REVIEW

**Review by wjcunningham7 — DISMISSED** [review]

**Comment by wjcunningham7** [comment]
@scottwn just noticed this will fail due to a syntax error.  The `uses` step does not contain `@ref` at the end.  See example of failure here: https://github.com/AgnostiqHQ/covalent/actions/runs/3132749986

**Comment by scottwn** [comment]
@wjcunningham7 can you confirm that MPL 2.0 is allowed?

**Comment by wjcunningham7** [comment]
> @wjcunningham7 can you confirm that MPL 2.0 is allowed?

confirmed

**Comment by wjcunningham7** [comment]
@scottwn the license workflow is failing

**Comment by scottwn** [comment]
@wjcunningham7 working now

**Review by wjcunningham7 — APPROVED** [review]

**Pull request merged**
