### PR TITLE
defer creation of server specific config entries

### PR DESCRIPTION
**Pull request by madhur-tandon**
Fixes https://github.com/AgnostiqHQ/covalent/issues/1430

- [x] I have added the tests to cover my changes.
- [x] I have updated the documentation and CHANGELOG accordingly.
- [x] I have read the CONTRIBUTING document.

### CODE REVIEW

**Comment by madhur-tandon** [comment]
Could appreciate a review @cjao 
CC: @AlejandroEsquivel / @kessler-frost

**Comment by madhur-tandon** [comment]
@kessler-frost can you re-trigger the RTD build...

**Comment by santoshkumarradha** [comment]
Thanks again @madhur-tandon. While @kessler-frost  does that, seems like RTD is failing with this error (I assume retreggiring might not help )

<details open>
<summary> Error message </summary>
<br>
Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/covalent/envs/1607/lib/python3.8/site-packages/sphinx/util/inspect.py", line 412, in safe_getattr
    return getattr(obj, name, *defargs)
AttributeError: module 'covalent.triggers' has no attribute 'dispatch'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/covalent/envs/1607/lib/python3.8/site-packages/sphinx/ext/autodoc/importer.py", line 110, in import_object
    obj = attrgetter(obj, mangled_name)
  File "/home/docs/checkouts/readthedocs.org/user_builds/covalent/envs/1607/lib/python3.8/site-packages/sphinx/ext/autodoc/__init__.py", line 318, in get_attr
    return autodoc_attrgetter(self.env.app, obj, name, *defargs)
  File "/home/docs/checkouts/readthedocs.org/user_builds/covalent/envs/1607/lib/python3.8/site-packages/sphinx/ext/autodoc/__init__.py", line 2606, in autodoc_attrgetter
    return safe_getattr(obj, name, *defargs)
  File "/home/docs/checkouts/readthedocs.org/user_builds/covalent/envs/1607/lib/python3.8/site-packages/sphinx/util/inspect.py", line 428, in safe_getattr
    raise AttributeError(name) from exc
AttributeError: dispatch

WARNING: autodoc: failed to import function 'dispatch_sync' from module 'covalent.triggers'; the following exception was raised:
Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/covalent/envs/1607/lib/python3.8/site-packages/sphinx/util/inspect.py", line 412, in safe_getattr
    return getattr(obj, name, *defargs)
AttributeError: module 'covalent.triggers' has no attribute 'dispatch_sync'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/covalent/envs/1607/lib/python3.8/site-packages/sphinx/ext/autodoc/importer.py", line 110, in import_object
    obj = attrgetter(obj, mangled_name)
  File "/home/docs/checkouts/readthedocs.org/user_builds/covalent/envs/1607/lib/python3.8/site-packages/sphinx/ext/autodoc/__init__.py", line 318, in get_attr
    return autodoc_attrgetter(self.env.app, obj, name, *defargs)
  File "/home/docs/checkouts/readthedocs.org/user_builds/covalent/envs/1607/lib/python3.8/site-packages/sphinx/ext/autodoc/__init__.py", line 2606, in autodoc_attrgetter
    return safe_getattr(obj, name, *defargs)
  File "/home/docs/checkouts/readthedocs.org/user_builds/covalent/envs/1607/lib/python3.8/site-packages/sphinx/util/inspect.py", line 428, in safe_getattr
    raise AttributeError(name) from exc
AttributeError: dispatch_sync
</details>

**Comment by madhur-tandon** [comment]
@santoshkumarradha I think re-trigger might help since my PR has nothing to do with the error encountered -- so maybe it's flaky at best...

But I can try investigating if re-trigger fails as well...
I say because before my last commit, everything passed...

**Comment by madhur-tandon** [comment]
@santoshkumarradha can you re-trigger the tests? docs passed but tests are flaky this time...

**Comment by madhur-tandon** [comment]
@santoshkumarradha This should be ready as well...

**Review by kessler-frost — APPROVED** [review]
Looks good 👍 !

**Pull request merged**
