### PR TITLE
Ci fix

### PR DESCRIPTION
**Pull request by scottwn**
- [x] I have added the tests to cover my changes.
- [x] I have updated the documentation and CHANGELOG accordingly.
- [x] I have read the CONTRIBUTING document.

### CODE REVIEW

**Comment by scottwn** [comment]
pre-commit.ci autofix

**Review by wjcunningham7 — APPROVED** [review]
very pretty

**Comment by wjcunningham7** [comment]
pre-commit.ci autofix

**Comment by wjcunningham7** [comment]
@scottwn looks like detect-secrets hook is complaining about secret inheritance in the workflows

**Review by wjcunningham7 — APPROVED** [review]

**Pull request merged**
