### PR TITLE
[WIP] Fix for Unnecessary electron metadata #20

### PR DESCRIPTION
**Pull request by Aobasi4**
- [ ] I have added the tests to cover my changes.
- [x] I have updated the documentation, VERSION, and CHANGELOG accordingly.
- [x] I have read the CONTRIBUTING document.

### CODE REVIEW

**Comment by Aobasi4** [comment]
I had a Couple of questions hence the WIP on the PR
1. After this change all tests seem to pass given the issue, where should I add the test for the change 
2. I will go back an edit the docs for the bug versioning, just wanted clarification on the tests and anything else I may be missing

**Comment by FyzHsn** [comment]
> I had a Couple of questions hence the WIP on the PR
> 
> 1. After this change all tests seem to pass given the issue, where should I add the test for the change

You could add a `test_default_constraint_values` function in `tests/covalent_tests/shared_files/defaults_test.py` checking that only backend argument is added.

> 2. I will go back an edit the docs for the bug versioning, just wanted clarification on the tests and anything else I may be missing

The rest looks good. :D Just need to add the changes to the CHANGELOG and the VERSION files.

**Comment by Aobasi4** [comment]
> > I had a Couple of questions hence the WIP on the PR
> > 
> > 1. After this change all tests seem to pass given the issue, where should I add the test for the change
> 
> You could add a `test_default_constraint_values` function in `tests/covalent_tests/shared_files/defaults_test.py` checking that only backend argument is added.
> 
> > 2. I will go back an edit the docs for the bug versioning, just wanted clarification on the tests and anything else I may be missing
> 
> The rest looks good. :D Just need to add the changes to the CHANGELOG and the VERSION files.

Awesome, thanks!

**Comment by Aobasi4** [comment]
For some reason the shared files did copy over when I forked the repo so I don't have the test file.  How should I resolve this? Also I'm not sure how to resolve the merge conflicts with the Changelog or version did I make the change incorrectly?

**Comment by FyzHsn** [comment]
> For some reason the shared files did copy over when I forked the repo so I don't have the test file. How should I resolve this? Also I'm not sure how to resolve the merge conflicts with the Changelog or version did I make the change incorrectly?

- Feel free to create the shared_files folder in the test folder.
- Ensure that you increase the patch version +1 compared to develop in the Version file.
- Attach the same version in Changelog and ensure that you're attaching the current (UTC) date.

**Pull request merged**
