### PR TITLE
Test Cancel Workflow in Dispatcher Service

### PR DESCRIPTION
**Pull request by Emmanuel289**
- [ ] I have added the tests to cover my changes.
- [ ] I have updated the documentation and CHANGELOG accordingly.
- [ ] I have read the CONTRIBUTING document.

### CODE REVIEW

**Comment by wjcunningham7** [comment]
@Emmanuel289 this issue may be related: https://github.com/AgnostiqHQ/covalent-staging/issues/333

**Comment by Emmanuel289** [comment]
> 



> @Emmanuel289 this issue may be related: [AgnostiqHQ/covalent-staging#333](https://github.com/AgnostiqHQ/covalent-staging/issues/333)

Alright. I will link it up. Though it has an empty scope

**Comment by Emmanuel289** [comment]
@kessler-frost Please let me know if I'm on the right track for the `test_cancel_workflow_execution` function or if I've missed something... I'll complete the bodies of the remaining two test functions by today.

**Comment by kessler-frost** [comment]
@Emmanuel289 Yeah, I think you're on the right track.

**Comment by Emmanuel289** [comment]
> @Emmanuel289 Yeah, I think you're on the right track.

Thanks!

**Pull request closed without merging**
