### PR TITLE
Executor resource deployment UX implementation

### LINKED ISSUE #1604: Executor Resource Deployment: CLI command group UX
## Overview

Add [deploy.py](http://deploy.py) file in `covalent/covalent_dispatcher/_cli/groups` where the [click.group](http://click.group) corresponding to deployment needs to be implemented to provide the following UI.

```bash
covalent deploy status
covalent deploy  up <executor_alias> [...args]
covalent deploy  down <executor_alias>
```

## UX

**$ covalent deploy status**

```python
	 Executor                Status           Description
   awsbatch                up               Provisioned Resources
   gcpbatch                down             No infrastructure provisioned
   azurebatch.             *up              Warning: Provisioning error, retry "up".
   braket                  *down            Warning: Teardown error, retry "down".
```

- The warning or “dirty” states should only be for partial provisioning/teardown any other errors should not affect the status of an executor

**$ covalent deploy \<executor\> up —help**

```python
Argument       Required       Default     
prefix         No             covalent
vcpu           No             2
memory         No             3.75
vpc-id         No             

```

> Note: to the above we want to add what the current executor values are for each arg

**$ covalent deploy \<executor\> up —dry-run --prefix="ae" --vpc-id="abcd"**

```python
Settings:
prefix: ae
vpc-id: abcd
...
```

- Show error during tf plan in the above (without verbose flag)
- Show terraform plan if `--verbose` provided* TP

**$ covalent deploy \<executor\> up —prefix=”ae” —vpc-id=”abcd”**

```python
Provisioning infrastructure for <executor>...

Settings:
prefix: ae
vpc-id: abcd

[===========================>                 ] 
Creating EFS Resource...

Completed.
```

- **Show current log line from terraform apply logs**
- We can extract Terraform error logs by specifying an ERROR log level and a specific terraform path to output from a specific run of a terraform command
- Show terraform logs if `--verbose` provided* TP
- If there is an issue during provisioning (partial deployment)
    - Instead of `Completed` → `Failed to provision resources, please re-run "up" command for this executor.`
- If there was an invalid input provided for executor args (can show one validation error at a time)
    - Instead of `Completed` → `Provided value for "vpc-id" is invalid` (We can show more specific errors extracted from pydantic validators in the plugin repo if possible)
- If the plugin version is old and does not have terraform scripts
    - Instead of `Provisioning infrastructure for <executor>...` → `Please update "<executor>" to the latest version to be able to deploy plugin.`
- If litmus test terraform & docker commands
- If terraform or docker is not installed:
    - Instead of `Provisioning infrastructure for <executor>...`  → `Please install "terraform/docker" to be able to deploy executor plugins.`

**$ covalent deploy <executor> down**

```python
Tearing down infrastructure for <executor>...
[===========================>                 ] 
Tearing down EFS resource...

Completed.
```

- **Show current log line from terraform teardown logs**
- Show terraform output if `—-verbose` flag
- *Same as “up” for old version
- *Same as “up” for missing docker/terraform
- If there is an issue during tear down (partial)
    - Instead of `Completed` → `Failed to teardown resources, please re-run "down command for this executor.`

## Acceptance Criteria

- [x] Implement CLI deploy command group with the commands specified in the design document that satisfy the intended UX leveraging `CloudResourceManager` 
- [x] Extend ``CloudResourceManager` to be able to extract terraform errors to display if there are any issues during provisioning or teardown
- [x] Extend ``CloudResourceManager` to be able to stream terraform logs to CLI if verbose flags are provided
- [ ] Extend ``CloudResourceManager` to throw any well defined errors (custom error objects) for any scenario that leads to an error state and catch these specific errors in the CLI command groups to render appropriate messages to end user

### PR DESCRIPTION
**Pull request by FyzHsn**
Fixes #1604 

- [ ] I have added the tests to cover my changes.
- [ ] I have updated the documentation and CHANGELOG accordingly.
- [ ] I have read the CONTRIBUTING document.

### CODE REVIEW

**Comment by santoshkumarradha** [comment]
@FyzHsn can you quickly comment here the left over items ?

**Comment by FyzHsn** [comment]
> @FyzHsn can you quickly comment here the left over items ?

Hey @santoshkumarradha, I'm seeing on the issue that the following acceptance criteria is not completed:
`Extend CloudResourceManager to throw any well defined errors (custom error objects) for any scenario that leads to an error state and catch these specific errors in the CLI command groups to render appropriate messages to end user`

The uncertainty in this leftover task is that we must read the logs and find a way to parse the error messages. Here's the complete list of error handling:
- We can extract Terraform error logs by specifying an ERROR log level and a specific terraform path to output from a specific run of a terraform command
- If there is an issue during provisioning (partial deployment)
- Instead of Completed → Failed to provision resources, please re-run "up" command for this executor.
- If there was an invalid input provided for executor args (can show one validation error at a time)
- Instead of Completed → Provided value for "vpc-id" is invalid (We can show more specific errors extracted from pydantic validators in the plugin repo if possible)
- If the plugin version is old and does not have terraform scripts
- Instead of Provisioning infrastructure for <executor>... → Please update "<executor>" to the latest version to be able to deploy plugin.
- If litmus test terraform & docker commands
- If terraform or docker is not installed:
- Instead of Provisioning infrastructure for <executor>... → Please install "terraform/docker" to be able to deploy executor plugins.

**Comment by kessler-frost** [comment]
The following issues will also need to be resolved in order for the respective executors to be supported by this:

- https://github.com/AgnostiqHQ/covalent-braket-plugin/issues/70
- https://github.com/AgnostiqHQ/covalent-ecs-plugin/issues/66
- https://github.com/AgnostiqHQ/covalent-awsbatch-plugin/issues/72
- https://github.com/AgnostiqHQ/covalent-awslambda-plugin/issues/87

**Comment by FyzHsn** [comment]
> The following issues will also need to be resolved in order for the respective executors to be supported by this:
> 
> * [Move IaC to plugin repo & Pydantic validation models covalent-braket-plugin#70](https://github.com/AgnostiqHQ/covalent-braket-plugin/issues/70)
> * [Move IaC to plugin repo & Add Pydantic validation models covalent-ecs-plugin#66](https://github.com/AgnostiqHQ/covalent-ecs-plugin/issues/66)
> * [Move IaC to plugin repo & Add Pydantic validation models covalent-awsbatch-plugin#72](https://github.com/AgnostiqHQ/covalent-awsbatch-plugin/issues/72)
> * [Move IaC to plugin repo & Pydantic validation models covalent-awslambda-plugin#87](https://github.com/AgnostiqHQ/covalent-awslambda-plugin/issues/87)

Yessir! I didn't mention them  earlier since they're quite trivial changes

**Review by kessler-frost — APPROVED** [review]
We'll need to create a separate PR for adding tests for this, I'll create an issue for it.

**Comment by kessler-frost** [comment]
Issue created for adding tests for these in a separate PR: https://github.com/AgnostiqHQ/covalent/issues/1860

**Review by AlejandroEsquivel — APPROVED** [review]
Great job here @mpvgithub @ArunPsiog @kessler-frost  , one potential enhancement is gracefully handling keyboard interrupts as if a user cancels out of this it may not terminate subprocesses

**Comment by kessler-frost** [comment]
Thanks @AlejandroEsquivel , I've created an issue for that 👍 .

**Pull request merged**
