### PR TITLE
UI executor label

### PR DESCRIPTION
**Pull request by Aravind-psiog**
- [ ] I have added the tests to cover my changes.
- [x] I have updated the documentation and CHANGELOG accordingly.
- [x] I have read the CONTRIBUTING document.

This pull request contains the following addition and changes:
- Added executor label, node id and node type to graph node UI
- Runtime has been modified to be more precise on the lattice and electron sidebar

### CODE REVIEW

**Comment by Prasy12** [comment]
@wjcunningham7 Covalent Dump logs step seems to fail. Can you help us with this?

**Comment by venkatBala** [comment]
> @wjcunningham7 Covalent Dump logs step seems to fail. Can you help us with this?

Hey @Prasy12 ... the logic around dumping covalent logs was missing a check... I've just updated the logic in #1126. Waiting for that to get merged. Once that's done, we can rebase this one and try again :)

**Comment by wjcunningham7** [comment]
should be good to go now @Prasy12

**Review by Prasy12 — DISMISSED** [review]

**Comment by Prasy12** [comment]
@wjcunningham7  @santoshkumarradha Can one of the AQ team review this and get this merged? Have asked @mshkanth to review as well.

**Review by mshkanth — APPROVED** [review]

**Review by AlejandroEsquivel — APPROVED** [review]
LGTM 👍

**Review by AlejandroEsquivel — APPROVED** [review]

**Pull request merged**
