### PR TITLE
[UnitaryHack] Highlight executor args/kwargs in the docs

### LINKED ISSUE #1637: Highlight executor args/kwargs in the docs
### What should we add?

In the [list of executor plugins](https://covalent.readthedocs.io/en/latest/plugins.html), several of them do not have a description of the available args and kwargs to the excecutor. The Dask executor is a good example that _does_ have them [here](https://covalent.readthedocs.io/en/latest/api/executors/dask.html#covalent.executor.executor_plugins.dask.DaskExecutor), although they do not have docstrings and are not documented. Note that for many of these executors, we will want to highlight not just the parameters but also the default values pulled from the default config.

In testing Covalent out with some colleagues, I realized they weren't used to inspecting functions/classes for the possible input parameters and were solely relying on what was in the RTD/repo READMEs, which meant they were missing out on any args/kwargs not directly described in the docs. The docs could better reflect this, particularly since it is under the API section.

### PR DESCRIPTION
**Pull request by WingCode**
- [x] I have added the tests to cover my changes.
- [x] I have updated the documentation and CHANGELOG accordingly.
- [x] I have read the CONTRIBUTING document.

closes #1637 

PRs required to close this issue

- https://github.com/AgnostiqHQ/covalent-awsbatch-plugin/pull/77
- https://github.com/AgnostiqHQ/covalent-ec2-plugin/pull/46
- https://github.com/AgnostiqHQ/covalent-slurm-plugin/pull/68
- https://github.com/AgnostiqHQ/covalent-awsbatch-plugin/pull/77
- https://github.com/AgnostiqHQ/covalent-braket-plugin/pull/72

### CODE REVIEW

**Comment by kessler-frost** [comment]
Thanks! Can you make sure it works for AWS Batch, as I merged your PR in `awsbatch` repo earlier today? I don't think something like `autoclass:: covalent_slurm_plugin.SlurmExecutor` will be sufficient. I feel like it is going to be trickier than it seems since the RTD will be unable to locate the `covalent_awsbatch` files.

**Comment by wjcunningham7** [comment]
> @kessler-frost In my local and with the respective covalent executors plugin installed, I able to generate documentation from the docstrings. This works for all of the executors mentioned in the [issue](https://github.com/AgnostiqHQ/covalent/issues/1637#issuecomment-1561747177). Kindly see the screenshot below for the Slurm Executor. image
> 
> I can add a step before generating the docs to install the respective covalent executors plugins so that RTD can find them on the python import paths. Do you think that this would be a good way to go about it?

@WingCode This is going to be required to close this issue.  However, ensure that plugin installation doesn't accidentally pull in the stable release of Covalent (as it's a dependency of each plugin).

**Comment by WingCode** [comment]
> > @kessler-frost In my local and with the respective covalent executors plugin installed, I able to generate documentation from the docstrings. This works for all of the executors mentioned in the [issue](https://github.com/AgnostiqHQ/covalent/issues/1637#issuecomment-1561747177). Kindly see the screenshot below for the Slurm Executor. image
> > I can add a step before generating the docs to install the respective covalent executors plugins so that RTD can find them on the python import paths. Do you think that this would be a good way to go about it?
> 
> @WingCode This is going to be required to close this issue. However, ensure that plugin installation doesn't accidentally pull in the stable release of Covalent (as it's a dependency of each plugin).

@kessler-frost / @wjcunningham7 Would you know a neat way of excluding `covalent` dependency during `pip install` ? The ways I know: 
1. Use `pip show` to get the dependencies, parse the output and exclude `covalent` dependency
2. Parse the requirements.txt from individual repository  & grep out `covalent`
3. Use `--no-deps` and install the other desired libraries only needed for autodoc RTD.

**Comment by kessler-frost** [comment]
@WingCode Unfortunately, nothing comes to mind off the top of the head for excluding `covalent` dependency. Maybe `pip`'s documentation will help, but I haven't explored that either.

**Comment by WingCode** [comment]
@kessler-frost Kindly let me know if you like some changes in this PR to get it merged :)

**Comment by kessler-frost** [comment]
@WingCode I still don't see the API reference here :sweat_smile: 

https://covalent--1680.org.readthedocs.build/en/1680/api/executors/awsbatch.html

image

**Comment by WingCode** [comment]
> @WingCode I still don't see the API reference here 😅
> 
> https://covalent--1680.org.readthedocs.build/en/1680/api/executors/awsbatch.html
> 
> image

@kessler-frost Thank you for following up
Locally I able to see it after performing `python3 setup.py docs` in a new conda environment, I able to see the API references :) 
image

I believe the issue is because the script over [here](https://readthedocs.org/projects/covalent/builds/21089764/) to make the docs available for this PR doesn't perform `python3 setup.py docs` to generate the docs. It can be confirmed here by looking at the [raw logs](https://readthedocs.org/api/v2/build/21089764.txt) where the executor plugins are not installed as per the setup.py docs step.

Could you tell me where I can find the script to generate the docs for this PR is persisted so that I can take a look at it?

**Comment by kessler-frost** [comment]
I think the file that you might wanna check out is `.readthedocs.yaml`. There is no one particular script that gets run but instead those steps that you mentioned are part of the predefined RTD action (correct me if I'm wrong @wjcunningham7 ). Next file of interest is the `doc/source/conf.py` which I'm guessing you already knew about.

**Comment by wjcunningham7** [comment]
I recommend looking at steps [here](https://docs.readthedocs.io/en/stable/build-customization.html) for extending the build process.

**Comment by WingCode** [comment]
@kessler-frost This issue is fixed finally! The autodoc is being rendered as expected for the plugins SSH, Slurm, AWS Braket, AWS Lambda, AWS EC2, AWS Batch, Google Batch.

**Comment by kessler-frost** [comment]
Thanks @WingCode 🚀! I'll take a look at this today.

**Review by kessler-frost — COMMENTED** [review]
Can you also remove this part from line 212 onwards in `doc/source/api/executors/awsbatch.rst`:

```
.. autoclass:: covalent.executor.EC2Executor
    :members:
:inherited-members:
```

It seems to be showing the EC2 Executor's API reference in AWS Batch's as well (https://covalent--1680.org.readthedocs.build/en/1680/api/executors/awsbatch.html#covalent.executor.EC2Executor). We must've missed it earlier.

Edit: I'll approve it again once it has been removed.

**Review by kessler-frost — APPROVED** [review]
Yeahp, verified all the mentioned executors' references and this looks gtg. Thanks @WingCode 🚀 !

CC: @wjcunningham7

**Comment by wjcunningham7** [comment]
Looks good to me!  @santoshkumarradha

**Review by wjcunningham7 — APPROVED** [review]

**Review by santoshkumarradha — APPROVED** [review]
LGTM ! sorry for the delay guys !

**Comment by santoshkumarradha** [comment]
CC: @sriranjanivenkatesan

**Pull request merged**
