### PR TITLE
Unit tests for UI back-end

### PR DESCRIPTION
**Pull request by Aravind-psiog**
- [x] I have added the tests to cover my changes.
- [x] I have updated the documentation and CHANGELOG accordingly.
- [x] I have read the CONTRIBUTING document.

### CODE REVIEW

**Comment by Aravind-psiog** [comment]
@wjcunningham7 We have added unit test cases for UI backend. Please help us merge this PR and let us know if anything had to be done.

**Comment by AlejandroEsquivel** [comment]
@Aravind-psiog this is marked as Draft, is this ready to be merged?

**Comment by Prasy12** [comment]
@AlejandroEsquivel This is ready for review and can be merged.

**Comment by cjao** [comment]
@AlejandroEsquivel @Prasy12 Is this still needed?

**Comment by Prasy12** [comment]
Yes @cjao , this is still relevant and needs to be tweaked a bit from our end before it can be merged.

**Comment by Prasy12** [comment]
@cjao @wjcunningham7 @tkdtaylor  This PR is ready for review, please let us know if you have any questions. Thanks.

**Comment by wjcunningham7** [comment]
@Aravind-psiog when I run pytest on this directory I get 42 failed, 38 passed.  are there specific instructions to run locally?

**Comment by Aravind-psiog** [comment]
> @Aravind-psiog when I run pytest on this directory I get 42 failed, 38 passed. are there specific instructions to run locally?

@wjcunningham7 Have added some requirements under tests/requirements.txt. Use the command `pip install -r tests/requirements.txt` and for running UI backend test cases use the command `python -m pytest -vv --reruns=0 tests/covalent_ui_backend_tests/ --cov=covalent_ui --cov-config=.coveragerc`

**Comment by wjcunningham7** [comment]
> > @Aravind-psiog when I run pytest on this directory I get 42 failed, 38 passed. are there specific instructions to run locally?
> 
> @wjcunningham7 Have added some requirements under tests/requirements.txt. Use the command `pip install -r tests/requirements.txt` and for running UI backend test cases use the command `python -m pytest -vv --reruns=0 tests/covalent_ui_backend_tests/ --cov=covalent_ui --cov-config=.coveragerc`

An example of an error I get is:
```
>       assert response.status_code == test_data["status_code"]
E       assert 400 == 200
E        +  where 400 = <Response [400 Bad Request]>.status_code
```

and when I print the response body I see
```
{'detail': [{'loc': ['path', 'dispatch_id'], 'msg': 'Dispatch ID 78525234-72ec-42dc-94a0-f4751707f9cd or Electron ID does not exist', 'type': None}]}
```

So it appears the mock database does not get seeded.

I also noticed that you're not using FastAPI's [TestClient](https://fastapi.tiangolo.com/tutorial/testing/) and also that you're using `fastapi_app.on_event` which has been recently changed to [Lifespan](https://fastapi.tiangolo.com/advanced/events/).  Since we already attach a lifespan to the main app, I suspect there is a conflict somewhere.

**Comment by Aravind-psiog** [comment]
@wjcunningham7 Looking into it https://github.com/AgnostiqHQ/covalent/pull/1414#issuecomment-1602601427

**Comment by ArunPsiog** [comment]
@wjcunningham7,

We have used `fastapi_app.on_event` to populate mock data for the test cases. If we use `lifespan`, we are suppose to mount our mock data creation function on [main.py](https://github.com/AgnostiqHQ/covalent/blob/tests-for-ui-backend/covalent_ui/api/main.py) as a parameter, which might create and delete the mock data on every server start. So we are planning to move mock environment creation away from the event handler.

For TestClient, we are using it in the  [TestClientTemplate](https://github.com/AgnostiqHQ/covalent/blob/tests-for-ui-backend/tests/covalent_ui_backend_tests/utils/client_template.py) class.

**Comment by ArunPsiog** [comment]
By default, Covalent install's the latest SQLAlchemy(i.e. [2.0.17](https://pypi.org/project/SQLAlchemy/2.0.17/)). We are using `sqlalchemy.ext.declarative.declarative_base` to initialize ORM models. The `sqlalchemy.ext.declarative.declarative_base` function was replaced by the new `sqlalchemy.orm.DeclarativeBase` function, [refer](https://docs.sqlalchemy.org/en/20/orm/mapping_api.html#sqlalchemy.orm.declarative_base) to below image for more details. 

image

@wjcunningham7, Could you suggest to us whether to upgrade the code base to support the latest version or restrict the version to [SQLAlchemy 1.4](https://pypi.org/project/SQLAlchemy/2.0.14/) ?

**Comment by Prasy12** [comment]
@wjcunningham7  https://github.com/AgnostiqHQ/covalent/pull/1702 is the PR that has made the version changes for SQL Alchemy which seems to be causing this.

**Comment by Prasy12** [comment]
We will anyway check on what needs to be changed so that the tests run successfully with latest requirements as well. 
cc : @ArunPsiog

**Review by wjcunningham7 — DISMISSED** [review]

**Comment by Prasy12** [comment]
@wjcunningham7 There are still changes to be pushed on this. Please don't merge this. Will convert as draft now. 
@mpvgithub Can you inform Will once you push the changes?

**Comment by mpvgithub** [comment]
@wjcunningham7,
Changes are made to the test cases under tests/covalent_ui_backend_tests to work with fast API version 0.93.0. 

You could use this command to run the test from the root folder
**python -m pytest -vv --reruns=0 tests/covalent_ui_backend_tests/ --cov=covalent_ui --cov-config=.coveragerc**

Kindly review this PR whenever you have time.

**Comment by wjcunningham7** [comment]
@mpvgithub just checking now that everything is reflected properly in codecov, then we can merge!

**Comment by Prasy12** [comment]
@wjcunningham7 Looks like one test is failing, please let us know if something needs to be changed or if you'll be able to resolve it.

**Review by wjcunningham7 — APPROVED** [review]

**Pull request merged**
