### PR TITLE
Update tests for v12

### PR DESCRIPTION
**Pull request by cjao**
- [ ] I have added the tests to cover my changes.
- [x] I have updated the documentation and CHANGELOG accordingly.
- [x] I have read the CONTRIBUTING document.

### CODE REVIEW

**Comment by cjao** [comment]
This is going to require some more additional work.  It turns out that many of the DBs in `execution_test.py` aren't mocked correctly, so the tests are actually hitting a DB on disk. I only found out after moving `test_results_post_process` b/c the real DB isn't initialized for the sdk tests. 

Also, I  think the integration tests questions can be decided later. For the time being, if the main goal is to remove the dependency on the DB, I'm thinking of just refactoring all the result object methods like `Result._update_node` to isolate the sqlalchemy commands into mockable functions. I'm reluctant to mock `_run_planned_workflow` entirely because the bugs that prompted `test_run_workflow_with_failing_nonleaf` and `test_run_workflow_with_failing_leaf` would not have been caught by the unit tests alone. The different types of node failures are handled in different code paths of `_run_planned_workflow`.

Marking as draft for now.

**Comment by cjao** [comment]
Hi @scottwn, I touched some other execution tests in that PR just to fix the db mocking so that they don't try to hit a persistent db, but those weren't originally in the scope of the PR. Mocking out the DB entirely for those tests would be considerably more involved and amount to fixing [#908](https://github.com/AgnostiqHQ/covalent/issues/908).

**Comment by cjao** [comment]
Hi @scottwn, I touched some other execution tests in that PR just to fix the db mocking so that they don't try to hit a persistent db, but those weren't originally in the scope of the PR. Mocking out the DB entirely for those tests would be considerably more involved and it would probably be easier to just fix [#908](https://github.com/AgnostiqHQ/covalent/issues/908).

**Comment by scottwn** [comment]
This is looking pretty good, can you also create a `MockDataStore` class in app_test.py so that `test_db()` isn't returning a `DataStore` that depends on the schemas defined on the SDK side? The `MockDataStore` can have a very trivial schema, just for testing that "results" are returned as expected.

**Comment by cjao** [comment]
Sorry I missed that last part! Will add it shortly.

**Comment by cjao** [comment]
@scottwn Have a look at the all-new MockDataStore : ).

**Review by scottwn — APPROVED** [review]

**Pull request merged**
