### PR TITLE
Update index.rst

### PR DESCRIPTION
**Pull request by rachana-uniyal**
Updated the corresponding hyperlinks.

- [ ] I have added the tests to cover my changes.
- [ ] I have updated the documentation, VERSION, and CHANGELOG accordingly.
- [ ] I have read the CONTRIBUTING document.

### CODE REVIEW

**Review by AlejandroEsquivel — DISMISSED** [review]

**Comment by AlejandroEsquivel** [comment]
@FyzHsn changes look ok, there is a Github action failing that is checking the CHANGELOG however. Do the VERSION and CHANGELOG need to be updated potentially as well?

**Comment by FyzHsn** [comment]
> @FyzHsn changes look ok, there is a Github action failing that is checking the CHANGELOG however. Do the VERSION and CHANGELOG need to be updated potentially as well?

@rachana-uniyal The VERSION and CHANGELOG files need to be updated.

**Comment by rachana-uniyal** [comment]
> > @FyzHsn changes look ok, there is a Github action failing that is checking the CHANGELOG however. Do the VERSION and CHANGELOG need to be updated potentially as well?
> 
> @rachana-uniyal The VERSION and CHANGELOG files need to be updated.

I have updated the VERSION and CHANGELOG file.

**Review by FyzHsn — APPROVED** [review]

**Comment by FyzHsn** [comment]
@rachana-uniyal Good job, this is ready to be merged!

**Pull request merged**
