### PR TITLE
Better error handling in generate_docs.py

### LINKED ISSUE #1833: Proper error handling in covalent/doc/generate_docs.py
### What should we add?

I would like to improve the code in the file `covalent/doc/generate_docs.py` by adding additional logging and adding a logging error if cmd.returncode != 0.
Seems like a simple fix. I would like to work on this issue for hacktoberfest 23.
Looking forward to get assigned on this issue.
Thanks

### Describe alternatives you've considered.

_No response_

### PR DESCRIPTION
**Pull request by THEGAMECHANGER416**
# Closes #1833 

- [x] I have updated the documentation and CHANGELOG accordingly.
- [x] I have read the CONTRIBUTING document.

### CODE REVIEW

**Comment by kessler-frost** [comment]
See connected issue.

**Comment by kessler-frost** [comment]
@THEGAMECHANGER416 you'll have to sign the CLA for the contribution to be mergeable. Thanks!

**Comment by THEGAMECHANGER416** [comment]
Done now, sorry about that

**Comment by kessler-frost** [comment]
No worries, let me see why the version check is failing.

**Review by kessler-frost — APPROVED** [review]

**Review by santoshkumarradha — APPROVED** [review]

**Pull request merged**
