### PR TITLE
Adding Module Dependencies feature

### PR DESCRIPTION
**Pull request by kessler-frost**
- [x] I have added the tests to cover my changes.
- [x] I have updated the documentation and CHANGELOG accordingly.
- [x] I have read the CONTRIBUTING document.

### CODE REVIEW

**Comment by santoshkumarradha** [comment]
@kessler-frost reminder on the usual list of docs changes for this as well along with this PR

CC: @sriranjanivenkatesan once the docs are up, please keep a tab to update it

**Comment by kessler-frost** [comment]
One thing to note here is that DepsModule are kind of a fake traditional “deps” in the sense that we don’t require them to be passed to the server as cloudpickle takes care of serializing the module when the serialization of the function happens.

**Comment by kessler-frost** [comment]
One drawback of this is that there we won't be recording the name of the module in the dispatcher server. @santoshkumarradha it's a UX question as in do we want to have a record or not? This is mostly an additive change and can be taken care of in a separate PR as well.

**Review by santoshkumarradha — APPROVED** [review]
UX is gtg 🤘

**Review by cjao — APPROVED** [review]

**Pull request merged**
