### PR TITLE
Executor string change

### PR DESCRIPTION
**Pull request by jkanem**
- [ ] I have added the tests to cover my changes.
- [x] I have updated the documentation and CHANGELOG accordingly.
- [x] I have read the CONTRIBUTING document.

### CODE REVIEW

**Comment by jkanem** [comment]
Related to, but does not resolve https://github.com/AgnostiqHQ/covalent-staging/issues/406

**Review by wjcunningham7 — DISMISSED** [review]
The only thing missing is an update to the how-to which describes custom executors.  Other than that looks good.

**Comment by jkanem** [comment]
The how-to is now updated.

**Review by AlejandroEsquivel — APPROVED** [review]
Given previous requested change is satisfied, will approve

**Pull request merged**
