### PR TITLE
[unitaryhack] Parity Generator

### PR DESCRIPTION
**Pull request by RamAIbot**
I have developed a covalent version of Pennylane parity generator classifier. I am successfully able to train the model and get accuracy as 1 after 25 iterations. But I am not able to plot the result as the "result" objects wait indefinitely. The file name of the example is "Covalent_pennylane_Parity_classifier" inside the machine learning tutorials folder.

image

### CODE REVIEW

**Comment by scottwn** [comment]
fixes #605

**Comment by Emmanuel289** [comment]
> Hi @scottwn , Is the PR accepted or do I need to change anything?

Hi @RamAIbot, just a quick update. The PR us currently under review by the team and no further action is required from your side for now. We will update you if changes need to be made though. Thanks!

**Comment by cjao** [comment]
The MNIST tutorial is a great example of how to guide the reader through what your code is trying to accomplish.

**Comment by scottwn** [comment]
duplicate of #669

**Pull request closed without merging**
