### PR TITLE
specify tutorials requirements

### PR DESCRIPTION
**Pull request by venkatBala**
- [ ] I have added the tests to cover my changes.
- [ ] I have updated the documentation and CHANGELOG accordingly.
- [ ] I have read the CONTRIBUTING document.

### CODE REVIEW

**Comment by wjcunningham7** [comment]
This should probably be split into one file per tutorial

**Comment by scottwn** [comment]
It's not clear to me what the use case is for this. Are we expecting users who are reading tutorials on RTD to also clone the notebook from GitHub? Seems like it's much more common to simply specify required packages in the docs.

**Comment by venkatBala** [comment]
> This should probably be split into one file per tutorial

@scottwn this was a requested change to (a) improve/standardize the tutorial's directory structure (b) secondly in case the repo is cloned... installing the dependencies per tutorial will become easier via the `requirements.txt' (c) when running the tutorials in our nightly CI, installing the dependencies for each will also become relatively easier.

**Review by scottwn — APPROVED** [review]

**Review by santoshkumarradha — DISMISSED** [review]
Organization in docs 👍   !

**Review by scottwn — APPROVED** [review]

**Review by santoshkumarradha — APPROVED** [review]
Approved from doc side !

**Pull request merged**
