### PR TITLE
UI filter dispatch list

### PR DESCRIPTION
**Pull request by Prasy12**
- [ ] I have added the tests to cover my changes.
- [x] I have updated the documentation and CHANGELOG accordingly.
- [x] I have read the CONTRIBUTING document.

This PR contains the following changes 
- Filter workflow dispatches by status on the GUI.
- Delete all workflow dispatches present in the database from the GUI and add filter level deletion of workflow dispatches as well. 
- Theme changes as part of latest wireframe.

### CODE REVIEW

**Comment by Prasy12** [comment]
@wjcunningham7  Can you help with the failed tests? Please note that unit testing is not complete on the UI side and will be partially increased from our end. We are prioritising the feature backlogs first and unit tests might come as a later PR. 

cc: @santoshkumarradha

**Comment by Prasy12** [comment]
Also added @AlejandroEsquivel as a reviewer as well as @AnnaGwen since we have updated the RTD as well.

cc : @santoshkumarradha @wjcunningham7

**Review by santoshkumarradha — APPROVED** [review]
Docs is good to go.

**Comment by Prasy12** [comment]
@AlejandroEsquivel @wjcunningham7 Can one of you review this and help us get this merged?

**Review by AlejandroEsquivel — APPROVED** [review]
LGTM

**Pull request merged**
