### PR TITLE
Hide postprocess of electrons and prettify names on the graph screen.

### PR DESCRIPTION
**Pull request by Prasy12**
- [ ] I have added the tests to cover my changes.
- [x] I have updated the documentation and CHANGELOG accordingly.
- [x] I have read the CONTRIBUTING document.

### CODE REVIEW

**Comment by Prasy12** [comment]
@santoshkumarradha Changes have been done. Except for the case when post process electron  fails, it will be hidden by default.
Have added @AlejandroEsquivel as reviewer.

cc : @mshkanth

**Review by tkdtaylor — COMMENTED** [review]
The changes look good, it would be good to have some basic tests for the new Prettify code though.

**Comment by mshkanth** [comment]
> The changes look good, it would be good to have some basic tests for the new Prettify code though.

Hi @tkdtaylor - We intend to bundle in unit tests along with every feature built on the UI. Sometimes, the timelines are steep, and we defer some unit tests to later. The fallback is that we have thorough manual QA done for every release from our side.

**Comment by santoshkumarradha** [comment]
> @santoshkumarradha - Going forward, could we bundle in a basic/intermediate amount of unit tests with every OS release we do. We are already at a 70% code coverage and writing on-going tests will push it higher.
> 
> The tradeoff is that development timelines might even be 2X. My suggestion is that, unless the time-to-market for a feature is very steep, Team Psi factors in the time needed to bundle in unit tests. Let me know what you think.

@mshkanth i would say that for front end, as long as manual qa is passed we can go ahead and backlog tests for critical features. But for usual steady state, I would agree to pack it with teats.

**Review by mshkanth — APPROVED** [review]
Minor - we can try to minimize false changes like space, indents going forward.

**Comment by mshkanth** [comment]
> > @santoshkumarradha - Going forward, could we bundle in a basic/intermediate amount of unit tests with every OS release we do. We are already at a 70% code coverage and writing on-going tests will push it higher.
> > The tradeoff is that development timelines might even be 2X. My suggestion is that, unless the time-to-market for a feature is very steep, Team Psi factors in the time needed to bundle in unit tests. Let me know what you think.
> 
> @mshkanth i would say that for front end, as long as manual qa is passed we can go ahead and backlog tests for critical features. But for usual steady state, I would agree to pack it with teats.

@Prasy12 - Good to deploy based on Santosh's feedback. Pls track unit tests for this feature in our backlog. Going forward, by default we can bundle in unit tests in our estimate unless we know it needs to deployed urgently.

**Comment by Prasy12** [comment]
@santoshkumarradha Since there is one failing test it cannot be automerged I guess. Can you help?

**Review by mshkanth — APPROVED** [review]

**Comment by santoshkumarradha** [comment]
> @santoshkumarradha Since there is one failing test it cannot be automerged I guess. Can you help?
pulling in @wjcunningham7  :D

**Pull request merged**
