### PR TITLE
move dask worker space to covalent cache

### PR DESCRIPTION
**Pull request by madhur-tandon**
Fix https://github.com/AgnostiqHQ/covalent/issues/1308

- [x] I have added the tests to cover my changes.
- [x] I have updated the documentation and CHANGELOG accordingly.
- [x] I have read the CONTRIBUTING document.

### CODE REVIEW

**Comment by madhur-tandon** [comment]
CC: @wjcunningham7 @AlejandroEsquivel @santoshkumarradha 

Could appreciate a review, thanks!
Also, please let me know if this option has to be passed while creating clusters inside different tests.
IMHO, using it within one test i.e. `test_cluster_info_cli` serves the purpose and is sufficient.

**Comment by madhur-tandon** [comment]
@santoshkumarradha This should be ready as well...

**Comment by madhur-tandon** [comment]
@kessler-frost resolved conflicts on CHANGELOG here, can you re-trigger `license`?

**Comment by madhur-tandon** [comment]
@kessler-frost suddenly the CI started failing and everything passed before my other PR was merged, do you have some ideas as to why this might happen?

**Comment by kessler-frost** [comment]
Yeah, I'm looking into it.

**Comment by kessler-frost** [comment]
@madhur-tandon , I think the reason might be that the DB directory doesn't exist when the `cli` is being imported (which eventually leads to trying to connect to the DB).

**Comment by madhur-tandon** [comment]
@kessler-frost Now that you fixed the issue with the DB directory creation here: https://github.com/AgnostiqHQ/covalent/pull/1622
(PS -- Sorry for missing that small detail earlier with my PR about deferring creation of server specific config directories)

This PR should be ready as well!

**Comment by kessler-frost** [comment]
Hey @madhur-tandon don't worry about it man, this is why we have tests 😄 .

**Review by kessler-frost — DISMISSED** [review]
This'll be a nice QoL improvement, thanks @madhur-tandon 🚀 !

**Comment by kessler-frost** [comment]
You might wanna update it with latest develop, and I'll approve it again 👍 .

**Comment by madhur-tandon** [comment]
@kessler-frost done, let's wait for CI to turn green I guess...

**Comment by madhur-tandon** [comment]
@kessler-frost Can you re-trigger functional tests? They should be unrelated to my change.

**Comment by kessler-frost** [comment]
Seems like they're failing on develop as well with the latest merge of #1624 . I'm looking into it.

**Comment by madhur-tandon** [comment]
@kessler-frost Hopefully this will be green as well now that functional tests should be fixed...

**Comment by kessler-frost** [comment]
🤞

**Comment by madhur-tandon** [comment]
@kessler-frost Ready to Go! 🚀

**Review by kessler-frost — APPROVED** [review]

**Pull request merged**
