### PR TITLE
Change `pennylane==0.33.1` to `pennylane>=0.31.1,<0.33.0` and remove redundant version from `tests/requirements.txt`

### PR DESCRIPTION
**Pull request by Andrew-S-Rosen**
- [ ] I have added the tests to cover my changes.
- [X] I have updated the documentation and CHANGELOG accordingly.
- [X] I have read the CONTRIBUTING document.

I removed the strict version pin on pennylane. It was forcing an upper-bound for the numpy version.

I saw that in #1845, it was mentioned that there can be issues installing Covalent with the most recent versions of pennylane. However, the test suite passes, so I'm curious where the error resides. If there is indeed an error, then something should be added to the test suite to flag it.

Sorry --- I'll continue to be annoying about fixing a dependency to a single version in setup.py unless it's critical. 😉

### CODE REVIEW

**Comment by kessler-frost** [comment]
Hi @Andrew-S-Rosen ! Thanks a lot for this 😄 , this exposed that we haven't removed the pennylane requirement from `tests/requirements.txt` which installs 0.31.1 after the normal `requirements.txt` installs 0.33.1 - which is why the tests don't fail. Try removing that line from `tests/requirement.txt` in this PR?

**Comment by kessler-frost** [comment]
Although, I do agree that a better solution would be to put a range on the `requirements.txt`, seems like `>=0.31.1,<0.33.0` should work.

**Comment by Andrew-S-Rosen** [comment]
@kessler-frost: Ah, that explains some things! You're right, the test suite fails (as expected) when removing the `pennylane` requirement in the `tests` folder.

So, for this PR, I have done the following:
- Removed `pennylane` from `tests/requirements.txt` so it's only in one plalce
- Changed it from a strict pin to 0.33.1 to a range from >=0.33.1,<0.33.1

**Comment by kessler-frost** [comment]
Thanks @Andrew-S-Rosen ! I think you've mentioned the version range wrong 😅 `pennylane>=0.33.1,<0.33.1` instead of `pennylane>=0.31.1,<0.33.0` (in the changelog as well).

**Comment by Andrew-S-Rosen** [comment]
@kessler-frost: Looks like I need to go back to middle school algebra!!

**Comment by kessler-frost** [comment]
Also, in the requirements.txt file the upper limit is 0.33.1 instead of 0.33.0 :P, which installs 0.33.0 and the test fails because of that 😅 .

**Comment by kessler-frost** [comment]
I'm sorry I should've reviewed it all in one go.

**Comment by Andrew-S-Rosen** [comment]
@kessler-frost not to worry, I realized the same. This is what happens when I open a PR while distracted. 😅 Sorry about that.

**Review by kessler-frost — APPROVED** [review]

**Review by santoshkumarradha — APPROVED** [review]

**Pull request merged**
