### PR TITLE
43 UI fixes

### LINKED ISSUE #43: UI: post-release fixes and features
@valkostadinov commented on [Tue Jan 25 2022](https://github.com/AgnostiqHQ/covalent-staging/issues/377)

This will track the development of post-release fixes and additional UI features:

- [x] re-order sidebar sections according to latest figma designs
- [x] update favicon
- [x] remove dispatch id from tab title
- [x] fit new uuids
- [x] show lattice and electron inputs
- [x] display error message on failed status for lattice and electron
- [x] extraction and display of executor attributes (`log_stdout`, `conda_env`, etc.)
- [x] log file output - display in Output tab of all available log file output. Initial solution will "tail" the files by periodically making an API call that fetches last n lines to simulate near real-time tailing.
- [x] auto-refresh result state on initial render of listing and graph pages
- [x] adjust theme text primary and secondary colors
- [x] truncate long electron/param names inside graph nodes at 70 chars, show full name elsewhere

### PR DESCRIPTION
**Pull request by valkostadinov**
Fixes #43

- [x] I have added the tests to cover my changes.
- [x] I have updated the documentation, VERSION, and CHANGELOG accordingly.
- [x] I have read the CONTRIBUTING document.

### CODE REVIEW

**Review by wjcunningham7 — DISMISSED** [review]
looks great!

**Comment by wjcunningham7** [comment]
> [CLA assistant check](https://cla-assistant.io/AgnostiqHQ/covalent?pullRequest=63) Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/AgnostiqHQ/covalent?pullRequest=63) before we can accept your contribution.You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/AgnostiqHQ/covalent?pullRequest=63) it.

@valentinkostadinov please sign on behalf of your employer

**Review by santoshkumarradha — APPROVED** [review]
Just ran it, additions changes and fixes work. 

Thanks @valkostadinov ! 🔥

**Review by santoshkumarradha — APPROVED** [review]
Good to go @valkostadinov ! 🔥

**Pull request merged**
