### PR TITLE
Dissolve loop to str join

### PR DESCRIPTION
**Pull request by boneyag**
A simple change:
Dissolve the for loop that concatenates a string to str.join.

### CODE REVIEW

**Comment by cjao** [comment]
Hi @boneyag, thanks for contributing. Before we go through the review, could you please open an issue to document what problem you are trying to address with this PR?

**Comment by boneyag** [comment]
> Hi @boneyag, thanks for contributing. Before we go through the review, could you please open an issue to document what problem you are trying to address with this PR?

Hi @cjao, I opened a new issue #1278 for the PR.

**Review by cjao — DISMISSED** [review]

**Comment by wjcunningham7** [comment]
@boneyag please add your changelog entry at the top of `CHANGELOG.md` under the `[UNRELEASED]` header.

**Comment by AnnaGwen** [comment]
Hi @boneyag , please update the version in the changelog.

**Review by wjcunningham7 — APPROVED** [review]

**Pull request merged**
