### PR TITLE
File Transfer Updates + RTD Revision

### PR DESCRIPTION
**Pull request by AlejandroEsquivel**
- [ ] I have added the tests to cover my changes.
- [x] I have updated the documentation and CHANGELOG accordingly.
- [x] I have read the CONTRIBUTING document.

### CODE REVIEW

**Review by venkatBala — DISMISSED** [review]
code changes lgtm... have to wait for the doc updates to be reviewed by @santoshkumarradha

**Review by santoshkumarradha — APPROVED** [review]

**Comment by santoshkumarradha** [comment]
Quick comment https://covalent--998.org.readthedocs.build/en/998/how_to/orchestration/file_transfers_for_workflows.html seems to not render properly.

**Comment by AlejandroEsquivel** [comment]
@santoshkumarradha addressed comments, section should be rendering correctly now

**Review by santoshkumarradha — APPROVED** [review]
GTG in docs

**Pull request merged**
