### PR TITLE
Add DispatchesDB and integrate with UI 

### PR DESCRIPTION
**Pull request by cjao**
- [ ] I have added the tests to cover my changes.
- [ ] I have updated the documentation, VERSION, and CHANGELOG accordingly.
- [ ] I have read the CONTRIBUTING document.

### CODE REVIEW

**Comment by cjao** [comment]
TODO: handle very large results.

**Comment by cjao** [comment]
From zoom:

The test centos is failing because Centos 7 ships sqlite 3.7.17 whereas this PR requires at least 3.24 as it uses sqlite [`upsert`](https://www.sqlite.org/lang_UPSERT.html).

**Review by scottwn — COMMENTED** [review]
I see a lot of static builds in the diff... do these need to be committed?

**Comment by wjcunningham7** [comment]
> I see a lot of static builds in the diff... do these need to be committed?

confirmed, does NOT need to be included

**Comment by wjcunningham7** [comment]
@scottwn @cjao the test that failed can be ignored

**Comment by scottwn** [comment]
@wjcunningham7 you want to use your God powers to merge? OK with me

**Pull request merged**
