### PR TITLE
Use pull_request_target for changelog_reminder workflow.

### LINKED ISSUE #581: Changelog Reminder workflow fails with HttpError: Resource not accessible by integration
### Environment

- **Covalent version**: 0.106.0
- **Python version**: 3.8
- **Operating system**: Ubuntu

### What is happening?

The [Changelog Reminder GitHub Actions workflow](https://github.com/AgnostiqHQ/covalent/blob/develop/.github/workflows/changelog_reminder.yml) is consistently [failing](https://github.com/AgnostiqHQ/covalent/actions/runs/2417511497) on external pull requests.

### How can we reproduce the issue?

Run automated checks on an external PR.

### What should happen?

The action should succeed and post a comment if the contributor has not updated the CHANGELOG.

### Any suggestions?

_No response_

### PR DESCRIPTION
**Pull request by cjao**
We don't build anything so this doesn't introduce any security
vulnerabilities.

- [ ] I have added the tests to cover my changes.
- [x] I have updated the documentation and CHANGELOG accordingly.
- [x] I have read the CONTRIBUTING document.

Closes #581.

### CODE REVIEW

**Comment by cjao** [comment]
I'm actually not sure why the Changelog reminder action doesn't appear at all.

**Review by scottwn — CHANGES_REQUESTED** [review]

**Comment by cjao** [comment]
@scottwn Is this good to go?

**Comment by scottwn** [comment]
I'm a little concerned that the changelog reminder didn't run on this PR at all. But if you want to merge this and then test the workflow again on other PRs I'm OK with that.

**Review by scottwn — APPROVED** [review]

**Comment by cjao** [comment]
Is there any way to retry the RTD build? I don't know why it's failing all of a sudden.

**Review by scottwn — APPROVED** [review]

**Pull request merged**
