### PR TITLE
fixing webapp build

### PR DESCRIPTION
**Pull request by wjcunningham7**
- [ ] I have added the tests to cover my changes.
- [ ] I have updated the documentation, VERSION, and CHANGELOG accordingly.
- [ ] I have read the CONTRIBUTING document.

### CODE REVIEW

**Comment by wjcunningham7** [comment]
PyPI workflow is good: [here](https://github.com/AgnostiqHQ/covalent/runs/5459860364)
Conda build script is good: [here](https://github.com/AgnostiqHQ/covalent/runs/5459860840)

**Comment by wjcunningham7** [comment]
documenting remaining problems:
- in `tests.yml` the test fail with the reason `yarn not found`, which is counter-intuitive since `yarn` should be installed on all GitHub runners
- The `Dockerfile` does not properly build, also due to an error with `yarn`. This can be reproduced locally with a simple `docker build .` in the root directory

**Comment by wjcunningham7** [comment]
@Emmanuel289 please take over from here

**Comment by valkostadinov** [comment]
@wjcunningham7 Submitted fix for Dockerfile and made analogous changed to.
- pypi.yml
- tests.yml
- meta.yaml
- setup.py

**Comment by Emmanuel289** [comment]
> @Emmanuel289 please take over from here



> @Emmanuel289 please take over from here

Thanks for the fixes @valkostadinov. Tests look good @wjcunningham7

**Pull request merged**
