### PR TITLE
example script to populate dummy result DB

### PR DESCRIPTION
**Pull request by scottwn**
- [ ] I have added the tests to cover my changes.
- [x] I have updated the documentation and CHANGELOG accordingly.
- [x] I have read the CONTRIBUTING document.

This PR adds an example script to populate a result DB with dummy data. It populates the electron and lattice tables. The electron deps table is WIP.

To run the script, first you must

- have Covalent installed _from this branch_ in a Conda environment
- have Covalent running

From the repo root, you can run the script with `python examples/example_db.py`. If you have Pandas installed, you can have the script print the tables by doing `python examples/example_db.py --show-tables`. 

@FyzHsn or @cjao might want to double check some of my field data, especially the filenames.

### CODE REVIEW

**Comment by scottwn** [comment]
@mshkanth @FyzHsn @wjcunningham7 if this is no longer needed then please close it

**Comment by Prasy12** [comment]
@scottwn 
Electron dependency table has no values when we execute the example script.
Attaching screenshots of all the tables. Can you please look at it and suggest a way for us to populate the electron dependency table as well 
Lattices
Electrons
Electron dependency

**Comment by scottwn** [comment]
@Prasy12 I added the electron dependency table to the script. Please confirm that this meets your needs and if so close this PR.

**Comment by mshkanth** [comment]
Hi @scottwn - We had also requested for actual/dummy files generated. Without the files & just the DB records, wouldn't help us by much. 

@Prasy12 Pls add any other context that I am un-aware of

**Comment by scottwn** [comment]
I've updated the script so that is creates all the files referenced in the table. @mshkanth please confirm that this meets your needs.

A couple notes, @FyzHsn for viz:
- I made the [arg_index](https://github.com/AgnostiqHQ/covalent/pull/733/files#diff-16b551c864dae9dcd147a9531878025fd164c59b699bb00dc4cea1a3d582316eR178) nullable, since it is often `None` in the link data. If you're interested, the script prints out all the link data and you can see the None values.
- All of the `info.log` files are empty, since this is not present in any node data that I can find and I'm not sure where it should be pulled from.

**Comment by FyzHsn** [comment]
> I've updated the script so that is creates all the files referenced in the table. @mshkanth please confirm that this meets your needs.
> 
> A couple notes, @FyzHsn for viz:
> 
> * I made the [arg_index](https://github.com/AgnostiqHQ/covalent/pull/733/files#diff-16b551c864dae9dcd147a9531878025fd164c59b699bb00dc4cea1a3d582316eR178) nullable, since it is often `None` in the link data. If you're interested, the script prints out all the link data and you can see the None values.

That makes sense, I'll make a note to update that in the schema.

> * All of the `info.log` files are empty, since this is not present in any node data that I can find and I'm not sure where it should be pulled from.

This is correct. It's a place holder for information suck as multiprocessing queue id, slurm id in the future.

**Comment by scottwn** [comment]
Working on addressing these items @mshkanth. Hope to have something for you tomorrow.

**Comment by scottwn** [comment]
>Right now, no workflow has a sub lattice. Can we simulate a few workflows that have a sub lattice structure?
I've added some sublattices to the script.
>All lattices & electrons have a status of NEW_OBJECT now. Can we simulate a few with completed/failed/other statuses? We can potentially directly change this in the DB but if it is easy to do from the script, we would like that.
I've added some `sleep` statements in the code that create various statuses. These can be changed by adjusting the `sleep` value on the [line indicated by the comment](https://github.com/AgnostiqHQ/covalent/pull/733/files#diff-21559f1e8a7ccc3f4cc93edaf6f07f67e4318f6b8831714c8adba09c61336e5eR249).
>In the electron table, parameters also have a type of 'electron' and their name contains the prefix ':parameter'. Believe this should be type=parameter and just the name?
I fixed this in the script.
>How/In what way is 'value_filename' different from 'results_filename' in the electrons table?
`value_filename` points to the pickle file that stores the value of a parameter electron. `results_filename` points to the pickle file that stores the result of a sublattice. This can be seen in V9 of the [database schema](https://drive.google.com/drive/folders/1HIkM7Dr_cgQpas_B00JCIkixGaertH7T).
>Also, can you help us with what will be stored in columns 'attribute' & 'key' in the electron table?
I've added the `key` field in the script. There is an ongoing [discussion](https://github.com/AgnostiqHQ/covalent/discussions/789) regarding `attribute_name`.

**Pull request closed without merging**
