### PR TITLE
[unitaryhack] Added Parity and Iris Classification

### PR DESCRIPTION
**Pull request by RamAIbot**
I have developed a covalent version of the Pennylane's Parity classification and Iris classification example. As mentioned in my other PR

[https://github.com/AgnostiqHQ/covalent/pull/641](url)

I have added the tutorial comments and added my files to the develop branch.

### CODE REVIEW

**Comment by cjao** [comment]
Hi @RamAIbot, this is looking better. However I cannot approve it yet since your markdown comments are lifted word-for-word from the [Pennylane tutorial]. Please rephrase them in your own words, and also briefly explain why are you adding `@ct.electron` and `@ct.lattice` decorators.

**Comment by cjao** [comment]
Please also include a reference to the original Pennylane tutorial.

**Comment by Emmanuel289** [comment]
> Hi @cjao, I have edited my tutorial section and added the references.

Hi @RamAIbot, some final "non-code" related tweaks need to be made in your tutorial notebooks. Could you make your branch writable so @cjao can push changes to your branch?

**Comment by cjao** [comment]
I can make these changes if I can push to your branch.

**Comment by cjao** [comment]
It is writable, thanks. We may push some minor revisions to your branch. The code generally looks ok. One tip to keep in mind is that adding an Electron decorator to a function will have no effect if that function is only used within another Electron. We have removed a few needless Electron decorators in your parity learner notebook.

**Review by Emmanuel289 — APPROVED** [review]

**Comment by Emmanuel289** [comment]
One last step before we can merge.... Since you are a first-time contributor, can you please sign the license agreement using the CLA assistant? Thanks! @RamAIbot

**Comment by Emmanuel289** [comment]
> 

Thanks!

**Review by Emmanuel289 — APPROVED** [review]

**Comment by nathanshammah** [comment]
@RamAIbot it seems like you have not signed up on unitaryHACK, please sign up to be able to claim the bounty https://airtable.com/shrJeycewBFqdot2B

**Pull request merged**
