### PR TITLE
OS Refactor Runner

### PR DESCRIPTION
**Pull request by kessler-frost**
- [x] I have added the tests to cover my changes.
- [x] I have updated the documentation, VERSION, and CHANGELOG accordingly.
- [x] I have read the CONTRIBUTING document.

Implementing the functionality of Runner.

### CODE REVIEW

**Review by FyzHsn — DISMISSED** [review]

**Comment by scottwn** [comment]
@kessler-frost was there an issue for this runner refactor?

**Comment by kessler-frost** [comment]
@scottwn No, I hadn't created an issue for this. I can create one if needed and then link that to this PR.

**Comment by scottwn** [comment]
@kessler-frost I don't think it's needed, just wanted to check

**Review by FyzHsn — DISMISSED** [review]
LGTM!

**Review by FyzHsn — APPROVED** [review]

**Review by FyzHsn — APPROVED** [review]

**Review by scottwn — APPROVED** [review]

**Pull request merged**
