### PR TITLE
[Hot-fix] UI electron attributes

### PR DESCRIPTION
**Pull request by Prasy12**
This PR contains the following fixes:
1.Electron executor and inputs information missing earlier will now be shown on the UI. 
2.Lazy loading on the UI has been optimised
3.Animated spinner is now available for running dispatches.

- [ ] I have added the tests to cover my changes.
- [ ] I have updated the documentation and CHANGELOG accordingly.
- [ ] I have read the CONTRIBUTING document.

### CODE REVIEW

**Comment by Prasy12** [comment]
@santoshkumarradha @wjcunningham7 Installing yarn seems to fail on centos, can you help me out with this?

**Comment by wjcunningham7** [comment]
> @santoshkumarradha @wjcunningham7 Installing yarn seems to fail on centos, can you help me out with this?

Weird. I'll take a look this morning.

**Comment by wjcunningham7** [comment]
Bug is documented here: https://github.com/nodesource/distributions/issues/1290#issuecomment-1217458013

**Comment by wjcunningham7** [comment]
Blocked on this PR: https://github.com/AgnostiqHQ/covalent/pull/1074

**Pull request merged**
