### PR TITLE
Updating images and copy across Concepts/Tutorials/How-To-Guides

### PR DESCRIPTION
**Pull request by Emmanuel289**
The following docs have been reviewed and updated in this PR:

- [Getting Started](https://covalent.readthedocs.io/en/latest/getting_started/index.html) guide has been updated with UI images.
- [Quantum Gravity](https://covalent.readthedocs.io/en/latest/tutorials/quantum_gravity/spacetime_classification.html) has been updated with missing images.
- [PennyLane Tutorial](https://covalent.readthedocs.io/en/latest/tutorials/machine_learning/pennylane_hybrid.html) has been reviewed for cell output containing user directories.
- [QAOA Tutorial](https://covalent.readthedocs.io/en/latest/tutorials/machine_learning/qaoa_maxcut.html) has been reviewed for syntax errors.

### CODE REVIEW

**Comment by Emmanuel289** [comment]
@AlejandroEsquivel Please can you point out which image is missing and has to be added in [Quantum Gravity](https://covalent.readthedocs.io/en/latest/tutorials/quantum_gravity/spacetime_classification.html) and which cell output in
[PennyLane Tutorial](https://covalent.readthedocs.io/en/latest/tutorials/machine_learning/pennylane_hybrid.html) contains the user directory.

**Comment by wjcunningham7** [comment]
@Emmanuel289 @AlejandroEsquivel the QG tutorial does not look ready.  It's missing one image (`qg_workflow_2.png`) and the third has not been updated.  additionally the cells need to be re-run since no output is showing.

Other images that need updating
- workflow in the concepts page
- mnist tutorial
- pennylane tutorial
- autoencoder tutorial needs cells to be executed
- quantum chemistry tutorial
- probably some other places

**Review by wjcunningham7 — CHANGES_REQUESTED** [review]
see other comment

**Comment by Emmanuel289** [comment]
> see other comment

@wjcunningham7 @AlejandroEsquivel  I went through the RTD and updated images/cells in various places:

-Concepts Page
-Machine Learning/Linear and convolutional autoencoders
-Machine Learning/MNIST classifier
-Machine Learning/Classical and quantum support vector machines
-Machine Learning/Using Covalent with PennyLane for hybrid computation
-Astronomy 
-Quantum Gravity (Accuracy of model seems low for 0.11)
- Using QAOA to solve the Max-Cut Problem (Looks good to me, no updates were made)
I ran into some dispatch errors in the following tutorials
- Training quantum embedding kernels for classification (fails dispatch at cell 7)
- 
Quantum Ensemble Classification (Fails dispatch at cells 8/9)

**Review by santoshkumarradha — DISMISSED** [review]
Docs are gtg !

**Review by wjcunningham7 — APPROVED** [review]

**Pull request merged**
