### PR TITLE
Fixing covalent pre-release

### PR DESCRIPTION
**Pull request by kessler-frost**
- [x] I have added the tests to cover my changes.
- [x] I have updated the documentation and CHANGELOG accordingly.
- [x] I have read the CONTRIBUTING document.

### CODE REVIEW

**Comment by kessler-frost** [comment]
After going through `dorny/paths-filter`'s code I found out that they are themselves checking whether the current action being run is on a PR or not. If the action is being run on a PR then they use Github's API to detect file changes, otherwise they use a separate mechanism which involves doing a `git branch --show-current`.

So, there are two viable solutions that come to my mind:
1. We don't run this action if the thing that we are running on is not a PR, or
2. We install `buster-backports` and enable `git branch --show-current` on Buster.

I prefer option 1, since we have already run this action once in the PR, and the tests are still going to run even without it if I'm not misunderstanding. But @scottwn @wjcunningham7 It's up to you guys to decide.

**Comment by wjcunningham7** [comment]
> After going through `dorny/paths-filter`'s code I found out that they are themselves checking whether the current action being run is on a PR or not. If the action is being run on a PR then they use Github's API to detect file changes, otherwise they use a separate mechanism which involves doing a `git branch --show-current`.
> 
> So, there are two viable solutions that come to my mind:
> 1. We don't run this action if the thing that we are running on is not a PR, or
> 2. We install `buster-backports` and enable `git branch --show-current` on Buster.
> 
> I prefer option 1, since we have already run this action once in the PR, and the tests are still going to run even without it if I'm not misunderstanding. But @scottwn @wjcunningham7 It's up to you guys to decide.

Let's just run all tests on develop. The filter was only needed to speed up PRs.

**Comment by kessler-frost** [comment]
I see, so you're suggesting we remove this action altogether?

**Comment by kessler-frost** [comment]
I think that's a good idea because even if we fix it for buster, it is still giving issues for centos. Removing this action in this PR.

**Review by wjcunningham7 — APPROVED** [review]

**Comment by scottwn** [comment]
the suggestion is to only run this action if the trigger is `pull-request`, so it doesn't run on `workflow-run`

**Pull request merged**
