### PR TITLE
Fixes issue #128: remove unnecessary blockquotes from "Creating custom executors" in the How-To guide

### PR DESCRIPTION
**Pull request by HaimHorowitzAgnostiq**
- [ ] I have added the tests to cover my changes.
- [ ] I have updated the documentation, VERSION, and CHANGELOG accordingly.
- [ ] I have read the CONTRIBUTING document.

### CODE REVIEW

**Comment by santoshkumarradha** [comment]
@FyzHsn @HaimHorowitzAgnostiq  also to note, the how-to title is wrong - it says How to customize executer in the list.

**Comment by FyzHsn** [comment]
> @FyzHsn @HaimHorowitzAgnostiq also to note, the how-to title is wrong - it says How to customize executer in the list.

@santoshkumarradha Would `How to create a custom executor` be a better title in index.rst.
@HaimHorowitzAgnostiq I think that the title in `How to choose the executors` could be changed to `How to choose an executor for a subtask` and also change the title within the corresponding How-To guide notebook.

**Comment by FyzHsn** [comment]
@cjao what's the status on this review?

**Comment by cjao** [comment]
Has the block quotes problem been already fixed? The only difference I see in this branch is the paragraph spacing:

`develop`
develop

`haim-issue128` (with your patches)
haim-issue128

**Comment by cjao** [comment]
It looks fine.

**Review by cjao — APPROVED** [review]
Looks fine

**Pull request merged**
