### PR TITLE
Fixes Reverse IP problem [unitaryhack]

### LINKED ISSUE #202: References to 0.0.0.0 should be changed to localhost
### What should we add?

0.0.0.0 is a special reserved IP and shouldn't be used to run the server. https://en.wikipedia.org/wiki/0.0.0.0

We should use `localhost` in docs instead.

Maybe the `covalent start` output can be enhanced so that it's more like Jupyter.
```
    To access the server, open this file in a browser:
        file:///Users/scott/Library/Jupyter/runtime/jpserver-15858-open.html
    Or copy and paste one of these URLs:
        http://localhost:8889/lab?token=b45cfa4204391c568859afb93d5823ab58e20ae195ae7063
     or http://127.0.0.1:8889/lab?token=b45cfa4204391c568859afb93d5823ab58e20ae195ae7063
```

### PR DESCRIPTION
**Pull request by divshacker**
Hey I have commited all the changes as suggested by @FyzHsn in issue #202 
This PR fixes #202 

- [ ] I have added the tests to cover my changes.
- [X] I have updated the documentation and CHANGELOG accordingly.
-  [X] I have read the CONTRIBUTING document.

### CODE REVIEW

**Comment by divshacker** [comment]
I have all the changes saved locally. I have just deleted my old repo and forked new one with the latest changes made. Then I cloned it locally and added my changes and pushed back. 
@scottwn let me know if there is any changes needed. 
Thanks

**Comment by divshacker** [comment]
I don't know why the tests are getting failed every time.

**Comment by scottwn** [comment]
Looks like the tests are failing because there's some issue connecting to `localhost`. @divshacker are these tests passing for you locally?

**Comment by divshacker** [comment]
> Looks like the tests are failing because there's some issue connecting to `localhost`. @divshacker are these tests passing for you locally?

I haven't tested that, As I don't know how to test it locally. 
May I get some instructions on how to test it locally please ?
Thanks

**Comment by scottwn** [comment]
Instructions on running tests are in CONTRIBUTING, let me know if something in that doc isn't clear

**Comment by divshacker** [comment]
-- Docs: https://docs.pytest.org/en/stable/warnings.html
=========================================================== short test summary info ============================================================
FAILED tests/functional_tests/docs_how_to_test.py::test_how_to_file[/home/divshacker/covalent/covalent/../doc/source/how_to/orchestration/construct_bash_task.ipynb-0]
FAILED tests/functional_tests/docs_how_to_test.py::test_how_to_file[/home/divshacker/covalent/covalent/../doc/source/how_to/execution/cancel_dispatch.ipynb-0]
======================================= 2 failed, 143 passed, 2 skipped, 6 warnings in 84.48s (0:01:24) ========================================

**Comment by scottwn** [comment]
what is the output from the test? there should be more verbose output under `FAILURES`

**Comment by divshacker** [comment]
This is just what I got when I ran `pytest -v` after following all initializations.
btw can we come to discord for better 1-1 communication ?

**Comment by Emmanuel289** [comment]
> This is just what I got when I ran `pytest -v` after following all initializations. btw can we come to discord for better 1-1 communication ?

Hi @divshacker. Thanks for your contribution on this PR. I will chat you on Discord in a bit with regards to this issue.

**Comment by divshacker** [comment]
From discussion  with @Emmanuel289 the problem is not in the repo but the system in which test run, In the testing piplines containers It is throwing some bash errors, Locally testing also shows some bash error. 
I don't think that will be much probematic. 
@scottwn Let me know your views
Thanks

**Review by scottwn — CHANGES_REQUESTED** [review]
deleting functional tests and the ui app is not acceptable

**Comment by divshacker** [comment]
> deleting functional tests and the ui app is not acceptable

Yes i know, I have just done this to test if it passes the pipeline test or not.

**Pull request closed without merging**
