### PR TITLE
Adding qelectron to stable covalent

### PR DESCRIPTION
**Pull request by kessler-frost**
- [ ] I have added the tests to cover my changes.
- [ ] I have updated the documentation and CHANGELOG accordingly.
- [ ] I have read the CONTRIBUTING document.

### CODE REVIEW

**Review by wjcunningham7 — APPROVED** [review]

**Comment by Andrew-S-Rosen** [comment]
@kessler-frost: This PR introduced several strict version pins, which can cause challenges for developers planning to use Covalent in their own packages. Are all of these version pins strictly necessary? We should relax as many as possible and replace with `>=`. Also, just to confirm, `pennylane` should be a core requirement and not something to be installed as an "extra"?

**Comment by kessler-frost** [comment]
@Andrew-S-Rosen : This was merged to one of the older stable branches where most of the things are working as expected. In `develop` the relaxed versions are already there and we will soon have a stable release based on our current `develop`.

The changes made in this PR and subsequently the place where this was merged to, are not to be considered as newer (or more up to date versions). They are just adding a new pretty much independent feature to an older covalent version.

**Comment by Andrew-S-Rosen** [comment]
@kessler-frost: Thanks for clarifying! However, when I look at `requirements.txt` in `develop`, it has the strict version pins still: https://github.com/AgnostiqHQ/covalent/blob/develop/requirements.txt. Should I be looking somewhere else?

**Comment by kessler-frost** [comment]
It has the strict ones for some of them (such as `lmdbm`, `pennylane`) as when tested we saw things to be only working on those. However, I see that you have a PR open for unlocking these versions, if things don't fail now there then let's relax those restrictions.

**Comment by Andrew-S-Rosen** [comment]
@kessler-frost: Thanks! The one I was really curious about was `orjson`. So, I'll iteratively try things and see how it fares. I decided to start with unpinning them all. Then I'll revised as-needed.

**Pull request merged**
