### PR TITLE
Fixed dynamic executor property assignment

### LINKED ISSUE #1669: Fix dynamic executor editing in Electrons
Tracking https://github.com/AgnostiqHQ/covalent/pull/1660#issuecomment-1559873222

### PR DESCRIPTION
**Pull request by kessler-frost**
- [x] I have added the tests to cover my changes.
- [x] I have updated the documentation and CHANGELOG accordingly.
- [x] I have read the CONTRIBUTING document.

Resolves #1669

### CODE REVIEW

**Comment by arosen93** [comment]
Would it be possible by chance to get an updated prerelease build following this PR, e.g. within the couple of weeks? :)

**Comment by kessler-frost** [comment]
Hey @arosen93 , definitely. I'd say ideally you should see a pre-release including the PR this week itself. @cjao should be back tomorrow to review this one (and probably merge as well), so we're good 👍 .

**Comment by arosen93** [comment]
Beautiful! Huge thank you!

**Review by cjao — APPROVED** [review]
Looks good @kessler-frost, thanks.

**Pull request merged**
