### PR TITLE
branding switchover

### PR DESCRIPTION
**Pull request by wjcunningham7**
- [ ] I have added the tests to cover my changes.
- [ ] I have updated the documentation and CHANGELOG accordingly.
- [ ] I have read the CONTRIBUTING document.

### CODE REVIEW

**Comment by wjcunningham7** [comment]
@santoshkumarradha please review the colors in the docs, feel free to make any changes to CSS colors.

**Comment by wjcunningham7** [comment]
before merging the URL in the README needs updating

**Comment by santoshkumarradha** [comment]
Hey @wjcunningham7 this looks good to go

Very small tweak if you can is to change the primary color in dark mode to the same color you have in white mode. Rest looks spick and span !

**Review by santoshkumarradha — DISMISSED** [review]

**Comment by santoshkumarradha** [comment]
Maybe another PR, but if you can, this statement is wrong and can be removed. 

Screen Shot 2022-04-14 at 4 37 19 PM

**Pull request merged**
