### PR TITLE
Basic structure to write a beginner tutorial

### PR DESCRIPTION
**Pull request by kessler-frost**
- [x] I have added the tests to cover my changes.
- [ ] I have updated the documentation, VERSION, and CHANGELOG accordingly.
- [x] I have read the CONTRIBUTING document.

This PR will introduce a very basic jupyter notebook explaining how a tutorial should be written for newcomers to covalent.

### CODE REVIEW

**Comment by kessler-frost** [comment]
Keep in mind, this a very loose structure and can be modified depending on what kind of tutorial is being written. It is not a full-fledged template. The only reason this file needs to be added to the develop branch is for anyone who is seeking to write a tutorial can refer to the points mentioned and hopefully it will help them.

**Review by wjcunningham7 — CHANGES_REQUESTED** [review]
This doesn't seem to render properly and it also needs a link from the main tutorials page.
https://covalent--114.org.readthedocs.build/en/114/tutorials/beginner_tutorial_template.html

**Comment by kessler-frost** [comment]
@wjcunningham7 I have added it to the tutorials.rst and fixed the render.
https://covalent--114.org.readthedocs.build/en/114/tutorials/tutorials.html

**Review by santoshkumarradha — CHANGES_REQUESTED** [review]
Looks great! One suggestion, instead of having it as a list in tutorial and as Jupiter notebook, can you add it as a rst file and link it in tutorial with a sentence like “ want to contribute tutorials? Here’s our guide” or something along that line.

**Review by santoshkumarradha — DISMISSED** [review]
🔥

**Comment by santoshkumarradha** [comment]
Also for inspiration - https://pennylane.ai/qml/demos_submission.html

**Review by wjcunningham7 — APPROVED** [review]

**Pull request merged**
